[project]
name = "ait"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grafo>=0.2.36",
    "instructor>=1.11.2",
    "pyyaml>=6.0.2",
]
